"""empty message

Revision ID: 8036f3aa8c86
Revises: 
Create Date: 2024-02-20 17:19:30.960363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8036f3aa8c86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    op.drop_table('citas')
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tipo_identificacion', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('numero_identificacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registro_medico', sa.Integer(), nullable=True))
        batch_op.alter_column('nombres',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.alter_column('nombres',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('registro_medico')
        batch_op.drop_column('numero_identificacion')
        batch_op.drop_column('tipo_identificacion')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('i')

    op.create_table('citas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('hora', mysql.TIME(), server_default=sa.text("'00:00:00'"), nullable=False),
    sa.Column('consultorio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctores.id'], name='FK_citas_doctores'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name='FK_citas_pacientes'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pacientes',
    sa.Column('Nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellidos', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('n_documento', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('celular', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
